### ISSUE TITLE
Browserify require fails without browserify-versionify

### ISSUE THREAD

**Issue by TablesawTablesawsen** [brightcove/videojs-contextmenu#1]
When attempting to require the plugin using browserify, an error is raised unless browserify-versionify is already installed as a dependency in the main project.

```
Error: Cannot find module 'browserify-versionify' from '[...]/node_modules/videojs-contextmenu'
```

This could be because the json package points main at "es5/plugin.js" (which still contains "`__VERSION__`") instead of "dist/videojs-contextmenu.js".

**Comment by gkatsev** [comment]
Oh, the generator still puts `browserify-versionify` into the devDependencies.

**Comment by misteroneill** [comment]
This should no longer be an issue since we're now using Rollup.
